# Generated by Django 4.0.4 on 2022-04-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=150)),
                ('imagem', models.ImageField(upload_to='blog/imagens')),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
