# Generated by Django 4.0.4 on 2022-05-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_conteudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
    ]
